version: '3.7'

services:
  server:
    volumes:
      - ./server:/app
      - static:/static
    env_file:
      - .env
    build: ./server
    ports:
      - "8005:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "85:80"
    depends_on:
      - server

volumes:
  static:

