version: '3.7'

services:
  server:
    volumes:
      - static:/static
    env_file:
      - ./server/.env
    build: ./server
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  static:

